# Generated by Django 3.2.6 on 2021-08-25 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BaseEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('related_video', models.CharField(max_length=255)),
                ('related_image', models.CharField(max_length=255)),
                ('main_body', models.TextField()),
                ('date', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('created', models.DateTimeField()),
            ],
        ),
    ]
